config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/about'
  get 'home/staff'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :posts do
    resources :comments
  end
  resources :comments
  resources :users
  resources :trips
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    validates :content, presence: true #checks if information has been entered.
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :set_comment, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_comment_author, only: [:edit, :update]
 
   def index
     if params[:post_id] && @post = Post.find_by_id(params[:post_id])
        @comments = @post.comments
     else
       @error = "That post doesn't exist" if params[:post_id]
       @comments = Comment.all
     end
   end
 
   def new
     #if it's nested and why find the post
     if params[:post_id] && @post = Post.find_by_id(params[:post_id])
       @comment = @post.comments.build
     else
       @error = "That post doesn't exist" if params[:post_id]
       @comment = Comment.new
     end
   end
 
   def create
     @comment = current_user.comments.build(comment_params)
     if @comment.save
       redirect_to comments_path, notice: 'Comment has been added.'
     else
       redirect_to new_comment_path, notice: 'Cannot submit with blank information.'
     end
   end
 
 
   def show
   end
 
   def edit
   end
 
   def update
     if @comment.update(comment_params)
       redirect_to comment_path(@comment)
     else
       render :edit
     end
   end

   def destroy
    @comment.destroy
    redirect_to posts_path, notice:'Comment has been deleted.'
   end
 
   private
 
   def comment_params
     params.require(:comment).permit(:content,:post_id)
   end
 
   def set_comment
     @comment = Comment.find_by(id: params[:id])
     if !@comment
       flash[:message] = "Comment was not found"
       redirect_to comments_path
     end
   end
 
   def redirect_if_not_comment_author
      redirect_to comments_path if @comment.user != current_user
   end
 end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1>Edit Comment</h1>
  </div>
  <div class="card-body">
    <%= form_for(@comment) do |f|%>
      <div class="field form-group">
        <%= f.text_field :content, class:"form-control", placeholder:'Edit your comment' %>
      </div>
      <div class="actions">
        <%= f.submit class:'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/index.html.erb
<div class="card">
  <div class="card-header">
    <% if @post %>
        <h1>Comments for <%= @post.name%></h1>
    <% else %>
        <h1>All Comments</h1>
    <% end %>
  </div>
  <div class="card-body">
    <% @comments.each do |c|%>
        <h5 class="card-title"><%= c.user.email %> says:</h5>
        <p class="card-text">"<%= c.content%>"</p>
        <p class="card-text">About this post: <strong><%= link_to c.post.name, post_path(c.post_id) %></strong></p>
        <% if c.user == current_user %>
          <%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-secondary' %>
        <% end %>
    <% end %>
  </div>
</div>
<br/>

app/views/comments/new.html.erb
<div class="card">
  <div class="card-header">
    <% if @comment.post %>
        <h1>New Comment for <%= @comment.post.name %></h1>
    <% else %>
        <h1>New Comment</h1>
    <% end %>
  </div>
  <div class="card-body">
    <%= form_for([@comment.post,@comment]) do |f|%>

    <%= f.hidden_field :post_id %>
  <div class="field form-group">
    <%= f.text_area :content, class:"form-control", placeholder:'Enter your comment'  %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-secondary'%>
  </div>

    <% end %>
  </div>
</div>

app/views/comments/show.html.erb
<div class="card">
  <div class="card-header">
    <h2><%= @comment.user.email%></h2>
  </div>
  <div class="card-body">
    <p><%= @comment.content%></p>
  </div>
</div>
<br/>

<% if @comment.user == current_user %>
  <%= link_to "Edit Comment", edit_comment_path(@comment), class:'btn btn-secondary'%>
<% end %>

<%= link_to 'Back', post_path(@comment.post_id), class:'btn btn-secondary' %>