config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/about'
  get 'home/staff'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :posts do
    resources :comments
  end
  resources :comments
  resources :users
  resources :trips
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :about, :staff]

  def about #static page, everyone can access this.
  end

  def staff #static page, everyone can access this
  end

  def after_sign_in_path_for(resource)
    app_dashboard_index_path
    # request.env['omniauth.origin'] || root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Strong Missions', root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Staff', home_staff_path, class:'nav-link' %>
      </li>
      <% if current_user.nil? %>
      <li class="nav-item">
        <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Past Experiences', posts_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Your Trips', trips_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link'%>
      </li>
      <% end %>

      <% if can? :manage, User %>
        <li class="nav-item">
          <%= link_to 'Admin Panel', rails_admin_path, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>

  </div>
</nav>

app/views/home/about.html.erb
<div class="card">
  <div class="card-header">
    <h1>The Strong Family</h1>
  </div>
  <div class="card-body">
    <p>I, Charlie Strong, am originally from Victoria, Texas, and my wife, Angela, is originally from Nueva Guinea, Nicaragua, although she has lived in Costa Rica almost all of her life. Our daughter, Anna Elena, was born in Costa Rica in March of 2009. I earned a Bachelor of Social Work degree from Southwest Texas State University and a Master of Divinity degree from Perkins School of Theology at Southern Methodist University. I worked in vocational ministry in the North Texas Conference of the United Methodist Church for almost 10 years, including youth, campus, and local church ministry and was formerly a registered Individual Volunteer with United Methodist Volunteers in Mission. God instilled a heart for missions within me while I was in my early twenties, and both this claim on my heart and the Gospel speak very clearly to me of Christ’s call to be in ministry to the poor.</p>

    <p>Through Angela’s life here and my travels and work within Costa Rica and Nicaragua, as well as the U.S., Mexico, Europe, Africa, and Russia, we have become acutely aware of a multitude of suffering children needing basic opportunities and resources not available to them due to their socioeconomic status. Strong Missions was created in 2003 to lend assistance to such children and their families as well as other deserving people facing struggles due to lower economic status.</p>

    <p>Our guarantee to you is that if you join us in this work, whether it be a mission trip or financial or prayerful support of one of our many children’s programs, that you will be able to make a real and lasting impression in the lives of the economically oppressed. In addition, you will develop a good understanding of the Costa Rican culture as well as a renewed heart for the mission of the Church to the poor.</p>

    <p><small>- Charlie, Angela and Anna Strong</small></p>
  </div>
</div>

app/views/home/index.html.erb
<div class="card">
  <div class="card-header">
    <h1>STRONG MISSIONS</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Welcome to Strong Missions</h5>
    <p class="card-text">To learn about us click the About Us tab in the navigation bar. To login/signup click the Login/Signup tab in the navigation bar.</p>
  </div>
</div>

app/views/home/staff.html.erb
<div class="card">
  <div class="card-header">
    <h1>Angela Gonzalez</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Empowered Communities Coordinator</h5>
    <p class="card-text">In addition to taking care of Charlie and Anna, Angela manages the kitchen at Strong Missions and helps with the logistics of the Loaves and Fishes feeding programs as well as Human Resources. Angela is currently finishing school for business management and hopes to run her own business in the future while still supporting the mission. She has a yellow belt in karate so make sure you stay on her good side!</p>
  </div>
</div>
<br/>
<div class="card">
  <div class="card-header">
    <h1>Roy Leon</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Program Assistant</h5>
    <p class="card-text">Roy is a native of Barranca, Puntarenas; he enjoys walking along the beach and watching the sunset while the foam vanishes in his footsteps. Roy enjoys working with people and always seeks to change the conditions of poverty in communities. He Loves surfing, travel, practicing martial arts, reading, and problem solving. He has worked the last 10 years with local development, housing, and public space projects.</p>
  </div>
</div>
<br/>
<div class="card">
  <div class="card-header">
    <h1>Wilberth Mora Gonzalez</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Construction Foreman</h5>
    <p class="card-text">Wilberth began working with Strong Mission in 2005. He works closely with all the groups and enjoys getting to know the teams. He is a dedicated worker and a pleasure to have as part of the Strong Missions family. His wife Elisabeth also works as a cook and they have 4 children and 3 grandchildren. His English is better than he lets on, so feel free to quiz him on the worksite.</p>
  </div>
</div>
<br/>
<div class="card">
  <div class="card-header">
    <h1>Warner Gonzalez Herra</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Construction</h5>
    <p class="card-text">Warner began working with Strong Missions in 2010. He is Wilberth’s brother and it is fun to have the brothers working together with the teams. When asked what he likes to do in his free time, his response was a smile and that he liked to work which isn’t a surprise coming from such a hard-working guy.</p>
  </div>
</div>