config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get 'home/about'
  get 'home/staff'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :posts do
    resources :comments
  end
  resources :comments
  resources :users
  resources :trips
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :users, through: :comments
    validates :name, presence: true #checks if information has been entered.
    validates :experience, presence: true #checks if information has been entered.
    #scope method shows the posts in descending order based on how many comments the post has. The post with most comments is at the top of the page. Used in the posts controller under the index method.
    scope :most_comments, -> {left_joins(:comments).group('posts.id').order('count(comments.post_id) desc')}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :correct_user, only: [:edit, :update, :destroy]
  
    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.most_comments #in post model. shows the post with most comments in descending order.
    end
  
    # GET /posts/1
    # GET /posts/1.json
    def show
    end
  
    # GET /posts/new
    def new
      @post = Post.new
    end
  
    # GET /posts/1/edit
    def edit
    end
  
    # POST /posts
    # POST /posts.json
    def create
      # @trip = Trip.new(trip_params)
      @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to posts_path, notice: 'Post was successfully created.'
      else
        redirect_to new_post_path, notice: 'Cannot leave information blank.' #if the information is left blank then it will keep them on the new post path and give them a notice.
      end
    end
  
    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      if @post.update(post_params)
        redirect_to posts_path, notice: 'Post was successfully updated.'
      else
        redirect_to edit_post_path, notice: 'Cannot Leave information blank.'  #if the information is left blank then it will keep them on the edit post path and give them a notice.
      end
    end
  
    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      redirect_to posts_path, notice: 'Post was successfully removed.' #only admin can delete post. delete comments first and then delete post. If you delete post with comments it will raise an error.
    end
  
    def correct_user #finds the post_id that is associated to the current_user id. if the user does not own that post then it will redirect them to the posts index page with a notice.
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: 'not authorized to edit this post' if @post.nil?
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = Post.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:name, :experience, :user_id)
      end
  end

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
<br/>
  <div class="card">
    <div class="card-header">
      <h4>Your Experience With Strong Missions</h4>
    </div>
    <div class="card-body">
  <div class="field form-group">
    <%= form.text_field :name, class:"form-control", placeholder:'Enter your group name'%>
  </div>

  <div class="field form-group">
    <%= form.text_area :experience, class:"form-control", placeholder:'Explain your experience helping Strong Missions' %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :post_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>

<br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
    </div>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form', post: @post %>
<br/>
<%= link_to 'Back', posts_path, class:'btn btn-secondary' %>
<%= link_to 'Show', @post, class:'btn btn-secondary' %> 

app/views/posts/index.html.erb
<div class="card">
  <div class="card-header">
    <h1>Past Experiences with Strong Missions</h1>
  </div>
  <div class="card-body">
    <% @posts.each do |post| %>
    <h5 class="card-title"><%= post.name %></h5>
    <p class="card-text"><%= post.experience %></p>
    <%= link_to 'Show', post_path(post), class:'btn btn-secondary' %>
    <% if post.user == current_user %>
      <%= link_to 'Edit', edit_post_path(post), class:'btn btn-secondary' %>
    <% end %>
    <br/><br/>
    <% end %>
  </div>
</div>
<br/>
<%= link_to 'New Post', new_post_path, class:'btn btn-secondary' %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>
<br/>
<%= link_to 'Back', posts_path, class:'btn btn-secondary' %>

app/views/posts/show.html.erb
<br/>
<div class="card">
  <div class="card-header">
    <h1><%= @post.name %></h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">By: <%= @post.user.email %></h5>
    <p class="card-text"><%= @post.experience %></p>
  </div>
</div>
<br/>
<%= link_to 'See all comments', post_comments_path(@post), class:'btn btn-secondary' %>
<br/><br/>
<%= link_to 'Add a new comment', new_post_comment_path(@post), class:'btn btn-secondary' %>
<br/>
<br/>
<div class="card">
  <div class="card-header">
    <h1>Comments</h1>
  </div>
  <div class="card-body">
    <% @post.comments.each do |c| %>
        <h5 class="card-title"><%= c.user.email %> says:</h5>
        <p class="card-text">"<%= link_to c.content, comment_path(c) %>"</p>
        <% if c.user == current_user %>
          <%= link_to 'Delete', c, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-secondary' %>
        <% end %>
    <% end %>
  </div>
</div>